# Nome do Workflow
name: Pipeline

# Evento que irá acionar a pipel ine
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download do Repositório
        uses: actions/checkout@v4       # https://github.com/actions/checkout

      - name: Setup Python
        uses: actions/setup-python@v5   # https://github.com/actions/setup-python
        with:
          python-version: '3.10'

      - name: Install Requirements
        run:  pip install flask pytest pylint

      - name: Unit Test
        run: python -m unittest -v test

      - name: Lint Test
        run: python -m pylint app.py --fail-under=7.0 --recursive=y --enable=W

  Deploy:
      runs-on: ubuntu-latest
      steps:
        - name: DockerHub build
          run: docker buildx build -t kevinalmeida:pipelineapp .

        - name: DockerHub Pull
          run: docker push kevinalmeida:pipelineapp 

